-- MySQL Script generated by MySQL Workbench
-- Tue May 14 17:16:44 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mbilka_baza_projekt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mbilka_baza_projekt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mbilka_baza_projekt` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;
USE `mbilka_baza_projekt` ;

-- -----------------------------------------------------
-- Table `mbilka_baza_projekt`.`Recepcja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mbilka_baza_projekt`.`Recepcja` (
  `idRecepcja` INT NOT NULL AUTO_INCREMENT,
  `Nazwa` VARCHAR(45) NOT NULL,
  `Adress` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRecepcja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbilka_baza_projekt`.`Pokoje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mbilka_baza_projekt`.`Pokoje` (
  `idPokoje` INT NOT NULL AUTO_INCREMENT,
  `Rzutnik` BIT(1) NOT NULL,
  `Pietro` VARCHAR(45) NOT NULL,
  `Nr_Pokoju` INT NOT NULL,
  `Recepcja_id` INT NOT NULL,
  PRIMARY KEY (`idPokoje`),
  INDEX `fk_Pokoje_Recepcja1_idx` (`Recepcja_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pokoje_Recepcja1`
    FOREIGN KEY (`Recepcja_id`)
    REFERENCES `mbilka_baza_projekt`.`Recepcja` (`idRecepcja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbilka_baza_projekt`.`SiP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mbilka_baza_projekt`.`SiP` (
  `idSiP` INT UNSIGNED NOT NULL,
  `Stanowisko` VARCHAR(45) NOT NULL,
  `Dostep_do_bazy_danych` BIT(1) NOT NULL,
  `Miejsce_Parkingowe` BIT(1) NOT NULL,
  PRIMARY KEY (`idSiP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbilka_baza_projekt`.`Klienci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mbilka_baza_projekt`.`Klienci` (
  `idKlienci` INT NOT NULL,
  `Nazwa_Firmy` VARCHAR(45) NULL,
  `Telefon` VARCHAR(10) NULL,
  PRIMARY KEY (`idKlienci`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbilka_baza_projekt`.`Projekty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mbilka_baza_projekt`.`Projekty` (
  `idProjekty` INT NOT NULL,
  `Koszt` DECIMAL(12,4) NULL,
  `Deadline` DATE NULL,
  `Klienci_id` INT NOT NULL,
  PRIMARY KEY (`idProjekty`),
  INDEX `fk_Projekty_Klienci1_idx` (`Klienci_id` ASC) VISIBLE,
  CONSTRAINT `fk_Projekty_Klienci1`
    FOREIGN KEY (`Klienci_id`)
    REFERENCES `mbilka_baza_projekt`.`Klienci` (`idKlienci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbilka_baza_projekt`.`Pracownicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mbilka_baza_projekt`.`Pracownicy` (
  `idPracownicy` INT NOT NULL AUTO_INCREMENT,
  `Imie` VARCHAR(45) NOT NULL,
  `Nazwisko` VARCHAR(45) NOT NULL,
  `Telefon` VARCHAR(10) NOT NULL,
  `Pokoje_idPokoje` INT NOT NULL,
  `SiP_id` INT NOT NULL,
  `Projekty_id` INT NOT NULL,
  PRIMARY KEY (`idPracownicy`, `Pokoje_idPokoje`, `SiP_id`, `Projekty_id`),
  INDEX `fk_Pracownicy_Pokoje1_idx` (`Pokoje_idPokoje` ASC) VISIBLE,
  INDEX `fk_Pracownicy_Stanowisko1_idx` (`SiP_id` ASC) VISIBLE,
  INDEX `fk_Pracownicy_Projekty1_idx` (`Projekty_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pracownicy_Pokoje1`
    FOREIGN KEY (`Pokoje_idPokoje`)
    REFERENCES `mbilka_baza_projekt`.`Pokoje` (`idPokoje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pracownicy_Stanowisko1`
    FOREIGN KEY (`SiP_id`)
    REFERENCES `mbilka_baza_projekt`.`SiP` (`idSiP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pracownicy_Projekty1`
    FOREIGN KEY (`Projekty_id`)
    REFERENCES `mbilka_baza_projekt`.`Projekty` (`idProjekty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbilka_baza_projekt`.`Szkolenia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mbilka_baza_projekt`.`Szkolenia` (
  `idSzkolenia` INT NOT NULL AUTO_INCREMENT,
  `Miejsce` VARCHAR(45) NULL,
  `Czas` DATE NULL,
  `SiP_id` INT NOT NULL,
  PRIMARY KEY (`idSzkolenia`),
  INDEX `fk_Szkolenia_Stanowisko1_idx` (`SiP_id` ASC) VISIBLE,
  CONSTRAINT `fk_Szkolenia_Stanowisko1`
    FOREIGN KEY (`SiP_id`)
    REFERENCES `mbilka_baza_projekt`.`SiP` (`idSiP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
